/*
 * File: app/model/Order.js
 *
 * This file was generated by Sencha Architect version 2.3.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Orders.model.Order', {
    extend: 'Ext.data.Model',

    idProperty: 'orderId',

    fields: [
        {
            name: 'id'
        },
        {
            name: 'orderNo',
            type: 'string'
        },
        {
            name: 'orderDate',
            type: 'string'
        },
        {
            name: 'shippedDate',
            type: 'string'
        },
        {
            name: 'balance',
            type: 'float'
        },
        {
            name: 'subTotal',
            type: 'float'
        },
        {
            name: 'shipping',
            type: 'float'
        },
        {
            name: 'tax',
            type: 'float'
        },
        {
            name: 'total',
            type: 'float'
        }
    ]
});