/*
 * File: app/view/EmployeeEdit.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Fulfill.view.EmployeeEdit', {
    extend: 'Ext.Container',
    alias: 'widget.employeeedit',

    config: {
        items: [
            {
                xtype: 'fieldset',
                id: 'employeeEditProperties',
                title: '',
                items: [
                    {
                        xtype: 'textfield',
                        itemId: 'employeeEditName',
                        label: 'Name',
                        name: 'name',
                        required: true,
                        autoCapitalize: true,
                        placeHolder: 'Wes Mantooth'
                    },
                    {
                        xtype: 'textfield',
                        id: 'employeeEditTitle',
                        label: 'Title',
                        name: 'title',
                        autoCapitalize: true,
                        autoComplete: true,
                        autoCorrect: true,
                        placeHolder: 'Lead Anchor'
                    }
                ]
            },
            {
                xtype: 'container',
                padding: 10,
                items: [
                    {
                        xtype: 'button',
                        id: 'saveEmployeeButton',
                        ui: 'action',
                        text: 'Save employee'
                    },
                    {
                        xtype: 'button',
                        id: 'removeEmployeeButton',
                        margin: '10 0 0 0',
                        ui: 'decline',
                        text: 'Remove employee'
                    }
                ]
            }
        ]
    }

});