/*
 * File: app/view/ItemList.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Fulfill.view.ItemList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.itemlist',

    requires: [
        'Ext.XTemplate'
    ],

    config: {
        disableSelection: true,
        emptyText: 'No items, but you look dashing all the same.',
        store: 'itemsStore',
        itemTpl: Ext.create('Ext.XTemplate', 
            '<div class="list-item">',
            '',
            '    <img class="product-thumbnail" src="imgs/{imgUrl}" />',
            '    ',
            '    <div class="product-name">#{itemId}: {name}</div>',
            '    ',
            '    <div class="product-info">',
            '        <div class="per-unit-price">${perUnitPrice}</div>',
            '        <div class="quantity-in-stock">{quantityInStock} in stock</div>',
            '    </div>',
            '',
            '</div>',
            {
                usMoney: function() {
                    return '$' + num.toFixed(2);
                },
                disableFormats: true
            }
        ),
        plugins: [
            {
                type: 'pullrefresh'
            }
        ]
    }

});