/*
 * File: app/view/PieBreakdown.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Fulfill.view.PieBreakdown', {
    extend: 'Ext.chart.PolarChart',
    alias: 'widget.pieBreakdown',

    requires: [
        'Ext.chart.series.Pie',
        'Ext.chart.interactions.Rotate'
    ],

    config: {
        store: 'pieChartDataStore',
        colors: [
            '#444444',
            '#138CBF',
            '#141414',
            '#04CC98'
        ],
        series: [
            {
                type: 'pie',
                xField: 'total'
            }
        ],
        interactions: [
            {
                type: 'rotate'
            }
        ]
    }

});