/*
 * File: app/view/SalesHistoryChart.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Fulfill.view.SalesHistoryChart', {
    extend: 'Ext.chart.CartesianChart',
    alias: 'widget.saleshistorychart',

    requires: [
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Bar'
    ],

    config: {
        store: 'salesHistoryStore',
        colors: [
            '#444444',
            '#138CBF',
            '#141414',
            '#04CC98'
        ],
        axes: [
            {
                type: 'category',
                renderer: function() {
                    var labelText = arguments[0];
                    return Ext.Date.format(labelText, 'n/j/Y');
                },
                fields: [
                    'totaledOrderDate'
                ],
                label: {
                    renderer: function(value) {
                        return 'test';
                    }
                },
                labelInSpan: true,
                style: {
                    stroke: '#000',
                    fill: 'rgb(143,203,203)',
                    lineWidth: 2
                }
            },
            {
                type: 'numeric',
                fields: [
                    'Enterprise',
                    'Individual',
                    'SMB',
                    'Team'
                ],
                grid: {
                    odd: {
                        fill: '#e8e8e8'
                    }
                },
                position: 'left'
            }
        ],
        series: [
            {
                type: 'bar',
                style: {
                    stroke: '#000',
                    fill: 'rgb(143,203,203)',
                    lineWidth: 2
                },
                xField: 'totaledOrderDate',
                yField: [
                    'Enterprise',
                    'Individual',
                    'SMB',
                    'Team'
                ]
            }
        ],
        legend: {
            xtype: 'legend'
        }
    },

    onUpdateLegendStore: function(store, record) {
        this.callParent(arguments);
        this.fireEvent('filterstatechange', record.get('index'), record.get('disabled'));
    }

});