/*
 * File: app/model/LineItem.js
 *
 * This file was generated by Sencha Architect version 2.3.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Fulfill.model.LineItem', {
    extend: 'Ext.data.Model',

    config: {
        idProperty: 'lineItemId',
        fields: [
            {
                name: 'lineItemId'
            },
            {
                name: 'itemId',
                type: 'string'
            },
            {
                name: 'description',
                type: 'string'
            },
            {
                name: 'quantityOrdered',
                type: 'int'
            },
            {
                name: 'quantityInStock',
                type: 'int'
            },
            {
                name: 'packDate',
                type: 'date'
            },
            {
                name: 'bin'
            },
            {
                name: 'lot'
            },
            {
                name: 'imgUrl'
            },
            {
                name: 'name'
            }
        ]
    }
});