/*
 * File: app/model/Orders.js
 *
 * This file was generated by Sencha Architect version 2.3.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Fulfill.model.Orders', {
    extend: 'Ext.data.Model',

    config: {
        idProperty: 'orderId',
        fields: [
            {
                name: 'orderId'
            },
            {
                name: 'orderDate',
                type: 'date'
            },
            {
                name: 'name'
            },
            {
                name: 'address'
            },
            {
                name: 'state'
            },
            {
                name: 'zip'
            },
            {
                name: 'phone'
            },
            {
                name: 'fax'
            },
            {
                name: 'total'
            },
            {
                name: 'city'
            },
            {
                name: 'category'
            }
        ]
    }
});