/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'LineItem',
        'Orders',
        'Item',
        'Employee'
    ],
    stores: [
        'LineItemsStore',
        'OrdersStore',
        'PieChartDataStore',
        'SalesHistoryStore',
        'ItemsStore',
        'OrdersByItemStore',
        'EmployeesStore'
    ],
    views: [
        'OrderDetail',
        'OrderList',
        'OrdersNavView',
        'OrderConfirm',
        'ItemPick',
        'Home',
        'Dashboard',
        'SalesHistoryChart',
        'PieBreakdown',
        'ItemList',
        'ItemDetail',
        'ItemsNavView',
        'EmployeesNavView',
        'EmployeeList',
        'EmployeeEdit'
    ],
    requires: [
        'Ext.DateExtras',
        'Ext.plugin.PullRefresh'
    ],
    controllers: [
        'NavController'
    ],
    icon: {
        57: 'resources/icons/Icon.png',
        72: 'resources/icons/Icon-72.png',
        114: 'resources/icons/Icon@2x.png'
    },
    name: 'Fulfill',

    launch: function() {

        Ext.create('Fulfill.view.Home', {fullscreen: true});
    }

});
