/*
 * File: app/view/Punch.js
 *
 * This file was generated by Sencha Architect version 2.3.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Timecard.view.Punch', {
    extend: 'Ext.Container',
    alias: 'widget.punch',

    config: {
        items: [
            {
                xtype: 'button',
                centered: true,
                cls: 'punchButton',
                itemId: 'punchInButton',
                ui: 'action',
                iconCls: 'arrow_right',
                text: 'Punch in'
            },
            {
                xtype: 'button',
                centered: true,
                cls: 'punchButton',
                disabled: false,
                itemId: 'punchOutButton',
                ui: 'action',
                iconCls: 'arrow_left',
                text: 'Punch out'
            },
            {
                xtype: 'label',
                centered: false,
                cls: 'punchTime',
                itemId: 'punchTime'
            }
        ]
    }

});