/*
 * File: app/view/TabPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Timecard.view.TabPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.tabpanel',

    requires: [
        'Timecard.view.Punch',
        'Timecard.view.PunchList'
    ],

    config: {
        tabBar: {
            docked: 'bottom'
        },
        items: [
            {
                xtype: 'punch',
                title: 'Punch',
                iconCls: 'add'
            },
            {
                xtype: 'punchlist',
                id: 'punchListButton',
                title: 'Punches',
                iconCls: 'bookmarks'
            }
        ]
    }

});