/*
 * File: app/store/LineItemsStore.js
 *
 * This file was generated by Sencha Architect version 2.3.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Fulfill.store.LineItemsStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Fulfill.model.LineItem'
    ],

    config: {
        model: 'Fulfill.model.LineItem',
        storeId: 'lineItemsStore',
        proxy: {
            type: 'direct',
            directFn: Fulfill.ss.DXOrders.getItemsByOrder,
            paramOrder: 'orderId',
            paramsAsHash: false,
            reader: {
                type: 'json'
            }
        },
        grouper: {
            groupFn: function(item) {
                if (item.get('packDate')) {
                    if (item.get('shipDate')) {
                        return 'Shipped';
                    } else {
                        return 'Packed';
                    }
                } else {
                    return 'Unpacked';
                }
            },
            sortProperty: 'packDate'
        }
    }
});