/*
 * File: app/store/OrdersByItemStore.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Fulfill.store.OrdersByItemStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Fulfill.model.Orders',
        'Fulfill.DirectAPI',
        'Ext.data.proxy.Direct',
        'Ext.data.reader.Json'
    ],

    config: {
        model: 'Fulfill.model.Orders',
        storeId: 'ordersByItemStore',
        proxy: {
            type: 'direct',
            directFn: 'Fulfill.ss.DXInventory.getOrdersByItem',
            paramOrder: 'itemId',
            reader: {
                type: 'json'
            }
        }
    }
});