/*
 * File: app/view/Breadcrumbs.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Orders.view.Breadcrumbs', {
    extend: 'Ext.Component',
    alias: 'widget.breadcrumbs',

    requires: [
        'Ext.XTemplate'
    ],

    cls: 'breadcrumbs',
    itemId: 'breadcrumbs',

    initComponent: function() {
        var me = this;

        me.addEvents(
            'breadcrumbactivate'
        );

        Ext.applyIf(me, {
            tpl: [
                '<tpl for=".">',
                '{% if (xindex < xcount) { %}',
                '    <span class="prev" data-card="{[xindex - 1]}">{.}</span> &gt;',
                '{% } else { %}',
                '    <span class="current">{.}</span>',
                '{% } %}',
                '</tpl>'
            ],
            listeners: {
                afterrender: {
                    fn: me.onBreadcrumbsAfterRender,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onBreadcrumbsAfterRender: function(component, eOpts) {
        component.mon(component.getEl(), 'click', function(e) {
        	var target = e.getTarget('.prev', 1);
            if (target) {
                component.fireEvent('breadcrumbactivate', component, parseInt(target.getAttribute('data-card'), 10));
            }
        });
    }

});