/*
 * File: app/view/ContactInfo.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Orders.view.ContactInfo', {
    extend: 'Ext.Component',
    alias: 'widget.contactinfo',

    requires: [
        'Ext.XTemplate'
    ],

    cls: 'contactInfo',
    margin: '0 0 10',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            tpl: [
                '<div class="name">{name}</div>',
                '<div class="address">{address}<br>{city}, {state} {zip}</div>',
                '<div class="phone">Phone: {phone}</div>',
                '<div class="phone">Fax: {fax}</div>'
            ]
        });

        me.callParent(arguments);
    }

});